[package]
name = "Stock_Trading_System"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amiquip = "0.4.2"
get_user_input = "0.1.1"
rand = "0.8.5"
scheduled-thread-pool = "0.2.7"
